NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')), # делаем так, чтобы все адреса из нашего приложения (news/urls.py) 
    # сами автоматически подключались когда мы их добавим.
    path('', include('protect.urls')),
    path('sign/', include(('sign.urls', 'sign'), namespace='sign')),
    path('account/', include('allauth.urls')),
    path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),
]


news/urls.py
from django.urls import path
from .views import NewsList, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, PostSearchView, PostCategoryView 
# импортируем наше представление

from .views import subscribe_to_category, unsubscribe_from_category
from .views import AppointmentView

#app_name = 'news_app' 

urlpatterns = [
    # path — означает путь. В данном случае путь ко всем статьям у нас останется пустым, позже станет ясно почему
    path('', NewsList.as_view(), name='news_list'), # т.к. сам по себе это класс, то нам надо представить этот класс в виде view. 
    # Для этого вызываем метод as_view
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'), # Ссылка на детали статьи
    path('add/', PostCreateView.as_view(), name='post_create'), # Ссылка на создание статьи
    path('edit/<int:pk>', PostUpdateView.as_view(), name='post_update'), # Ссылка на редактирование статьи
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'), # Ссылка на удаление статьи
    path('search/', PostSearchView.as_view(), name='post_search'), # Ссылка на поиск статьи
    path('make_app/', AppointmentView.as_view(), name='make_app'),
    path('category/<int:pk>', PostCategoryView.as_view(), name='category'), # Ссылка на категории
    path('subscribe/<int:pk>', subscribe_to_category, name='subscribe'), # Ссылка на подписчиков
    path('unsubscribe/<int:pk>', unsubscribe_from_category, name='unsubscribe'), # Ссылка на отписку
]

sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me

urlpatterns = [
     path('login/', LoginView.as_view(template_name = 'sign/login.html'), name='login'),
     path('logout/', LogoutView.as_view(template_name = 'sign/logout.html'), name='logout'),
     path('signup/', BaseRegisterView.as_view(template_name = 'sign/signup.html'), name='signup'),
     path('upgrade/', upgrade_me, name = 'upgrade'),

]

sign/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label = "Email")
    first_name = forms.CharField(label = "Имя")
    last_name = forms.CharField(label = "Фамилия")

    class Meta:
        model = User
        fields = ("username", 
                  "first_name", 
                  "last_name", 
                  "email", 
                  "password1", 
                  "password2", )
     
        
class CommonSignupForm(SignupForm):
    
    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user

sign/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from .models import BaseRegisterForm
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = '/'


@login_required
def upgrade_me(request):
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        authors_group.user_set.add(user)
    return redirect('/')

templates/sign/login.html
{% extends "flatpages/default.html" %}

{% block content %}
<div class="text-start">
    <br>
    <h1><a href="/">Simple SignUp/SignIn app</a></h1>
    <h2> Войти в систему </h2>
    <form method="post" action="{% url 'sign:login' %}">
        {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" value="Войти">
        
    </form>
    
    <button> <a href="/sign/signup"> Регистрация </a></button>
</div>

{% endblock %}

templates/sign/logout.html
{% extends "flatpages/default.html" %}

{% block content %}
<br>
<h2> Вы вышли из системы </h2>
{% endblock %}

templates/sign/signup.html
{% extends "flatpages/default.html" %} 

{% block content %}
    <div class="text-start">
        <br>
        <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        <br>
        <h2> Регистрация </h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Продолжить">
        </form> 
    </div>
{% endblock %}